### ISSUE TITLE
Cannot send StructMatlabData from Java to Matlab

### ISSUE THREAD

**Issue by m-morelli** [viatra/massif#59] opened 2017-09-26 09:58 UTC
Hello, this issue has the same setup of issue #58. That means
- running Matlab instance
- Java program connected to it through meaningful command evaluator and factory
- Matlab function defined as `function myTest___XYZ__DRF(a)    save 'xxx.mat' a;    end`

Now the data I have in Java, I want to package them into a `StructMatlabData`. Here's how I do it:

    StructMatlabData s = new StructMatlabData();
    s.addData("foo", new Handle(1.0));
    s.addData("bar", new Handle(2.0));

When I attempt to execute the Matlab function providing it `s` as input

    commandFactory.customCommand("myTest___XYZ__DRF", 0).addParam(s).execute()
nothing happens, i.e., the `xxx.mat` file is not created.

If I recover the last error message

    commandFactory.getLastErrorMessage().execute()
I get `Variable 'a' not found.`.

So, no data at all is apparently sent from the Java program to Matlab.

Any hints?
Thanks.
Matteo

**Comment by abelhegedus** [comment] 2017-09-26 10:17
It seems that Struct as a parameter is not supported, see https://github.com/viatra/massif/blob/master/plugins/hu.bme.mit.massif.communication/src/hu/bme/mit/massif/communication/datavisitor/ParameterVisitor.java#L68

**Comment by m-morelli** [comment] 2017-09-26 10:35
Thanks Abel for your reply. Note that If I change the Matlab function to not take inputs and return a struct and do

    IVisitableMatlabData z = commandFactory.customCommand("myTest___XYZ__DRF", 1).execute();
the variable `z` does contain the right struct.

So apparently *sending* a Struct (as input parameter) is not supported, whereas *getting* a Struct (as return parameter) is...

**Comment by abelhegedus** [comment] 2017-09-26 11:01
Note that I think the MatlabData contains the right values in both cases, but the visitors that map from MatlabData to the Matlab command interface are lacking. For the processing of returned values, you can check [CommandEvaluatorImpl](https://github.com/viatra/massif/blob/master/plugins/hu.bme.mit.massif.communication.commandevaluation/src/hu/bme/mit/massif/communication/commandevaluation/CommandEvaluatorImpl.java#L167) and [CommandEvaluatorMCImpl](https://github.com/viatra/massif/blob/master/plugins/hu.bme.mit.massif.communication.matlabcontrol/src/hu/bme/mit/massif/communication/matlabcontrol/CommandEvaluatorMCImpl.java#L159)

**Comment by imbur** [comment] 2017-11-09 04:56
Yes, I can confirm Abel's statement: currently passing structs as parameters are not supported, as it is a big `TODO` here: https://github.com/viatra/massif/blob/master/plugins/hu.bme.mit.massif.communication/src/hu/bme/mit/massif/communication/datavisitor/ParameterVisitor.java#L68

**Comment by imbur** [comment] 2017-11-09 06:13
Since this method was not used before, I added an initial implementation that works the way described in the first comment in this issue for simple MATLAB data.

**Comment by abelhegedus** [comment] 2018-11-19 09:54
Closing for now, please reopen with specifics if still relevant. Thanks!

**Closed by abelhegedus** 2018-11-19 09:54 UTC
Labels: enhancement
