### ISSUE TITLE
Exporting model does not work

### ISSUE THREAD

**Issue by GaraziJuez** [viatra/massif#48] opened 2017-06-05 11:55 UTC
Hello,

we are encountering an issue when trying to export from Massif to Simulink following "sldemo_clutch_import_demo.simulink"  example.  
Eclipse Mars, Massif Release is 0.5.0: EMF and IncQuery 1.0 are used.

Please find below more information regarding the problem occurred:

"Exporting model sldemo_clutch_import_demo..." has encountered a problema. An internal error occurred during: "Exportingmodel sldemo_clutch_import_demo..."
An internal error occurred during "Exporting model sldemo_clutch_import_demo...". Exception occurred while evaluating command!

Thank you very much for your help!
Garazi

**Comment by imbur** [comment] 2017-06-05 17:52
What version of Matlab are you using, and which connector (Matlabcontrol or Command evaluation server)? In Simulink, no model is created at all? Please check the Matlab workspace variables used while exporting as well, for they might provide further information regarding this issue.

**Comment by GGBAQQ** [comment] 2017-07-28 08:37
Hi,When I exported the simulink model, there was a mistake!
The details are as follows:
!
ENTRY hu. Bme. MIT. Massif. Simulink. API 4 0 16:30:54 2017-07-28. 494
!
The MESSAGE The block 'sldemo_engine_export/Combustion with sourceBlock' simulink/Ports & Subsystems/Subsystem could not be added

Junit error:
Java. Lang. IndexOutOfBoundsException: Index: 0, Size: 0
The at Java. Util. ArrayList. RangeCheck (Unknown Source)
The at Java. Util. ArrayList. Get (Unknown Source)
At hu.bme.mit.massif.com munication. Datatype. CellMatlabData. GetData (CellMatlabData. Java: 42)
The at hu. Bme. MIT. Massif. Simulink. API. Exporter. CreateConnectionFromSingleConnection (Exporter. Java: 915)
The at hu. Bme. MIT. Massif. Simulink. API. Exporter. ExportLines (Exporter. Java: 755)
The at hu. Bme. MIT. Massif. Simulink. API. Exporter. ExportBlocks (Exporter. Java: 511)
The at hu. Bme. MIT. Massif. Simulink. API. Exporter. Export (Exporter. Java: 264)
The at hu. Bme. MIT. Massif. Examples. API. ExporterExample. ExampleExport (ExporterExample. Java: 59)


I use the based running server within the running Matlab instance itself. Please help me, thanks

**Comment by GaraziJuez** [comment] 2017-08-08 13:29
Dear Marton,

first of all sorry for the delay on the response.
 We use Matlabcontrol and  when we export the "sldemo_clutch_import_demo.simulink" example from Massif to Simulink the following code is visualized on Matlab command line:

```
Warning: The block parameter 'DataType' on 'sldemo_clutch_import_demo/Friction Model/Fn' has been deprecated.
Getting/Setting the value of this parameter is no longer allowed. You can get/set the data type using parameter
'OutDataTypeStr' instead. 
Warning: The block parameter 'DataType' on 'sldemo_clutch_import_demo/Friction Model/Fn' has been deprecated.
Getting/Setting the value of this parameter is no longer allowed. You can get/set the data type using parameter
'OutDataTypeStr' instead. 
Warning: The block parameter 'DataType' on 'sldemo_clutch_import_demo/Friction Model/Fn' has been deprecated.
Getting/Setting the value of this parameter is no longer allowed. You can get/set the data type using parameter
'OutDataTypeStr' instead. 
Invalid setting in Inport block 'Fn' for parameter 'DataType'
```
Triying to solve and outline the issue, we have decided to remove the Friction Model block and export it again. This time we have got the same error applied to "'**sldemo_clutch_import_demo/Locked/Tin**' " block.  After removing Locked completely, a .slx has been created. Even if blocks are generated within the .slx file no connection between them can be seen. 

Thanks you very much!
Best regards,
Garazi

**Comment by abelhegedus** [comment] 2017-08-08 13:51
```
Warning: The block parameter 'DataType' on 'sldemo_clutch_import_demo/Friction Model/Fn' has been deprecated.
Getting/Setting the value of this parameter is no longer allowed. You can get/set the data type using parameter
'OutDataTypeStr' instead. 
```

This is a known issue with newer versions of Matlab, I have modified Massif in https://github.com/viatra/massif/commit/b1cf70750bd3999cc28c51ced7bf4310c9cb9aef to attempt to fix this. You can test it by trying the latest integration build: https://github.com/viatra/massif#integration-builds

**Comment by GaraziJuez** [comment] 2017-08-09 09:50
Hi Abel,

thank you very much for your rapid response.

We understand there  is a bug we need to fix. However, since we used  Oomph  for installing Massif ([https://github.com/viatra/massif/wiki/DevelopersGuide]), we are getting a bit lost on how we should proceed in order to fix it. Any help would be really useful.

Thank you,
Garazi

**Comment by GaraziJuez** [comment] 2017-08-09 09:58
Hi Abel,

thank you very much for your rapid response.

We understand there is a bug we need to fix. However, since we used Oomph for installing Massif
(https://github.com/viatra/massif/wiki/DevelopersGuide), we are getting a bit lost on how we should proceed in order to fix it. Any help would be really useful.

Thank you,
Garazi

**Comment by abelhegedus** [comment] 2017-08-09 10:03
The bug _should be_ already fixed in Massif, you just need to get a more up-to-date version.

I assume you have one of the Massif update sites (and probably EMF-IncQuery) added to a repository list in your Targlet task in the Oomph setup and one or more features added to the list of requirements.

If you are still using Massif 0.5.0 with EMF-IncQuery, you will have to modify the repository list to include the update site listed on https://github.com/viatra/massif#integration-builds and add the VIATRA update site http://download.eclipse.org/viatra/updates/release/ (see https://github.com/viatra/massif#prerequisites ). You may also have to update the version ranges of the requirements to allow Massif 0.6.0 to be installed into the Target Platform.

If you have added Massif to the P2 director task, the process is very similar, but the update sites are in the same list as the requirements.

> However, since we used Oomph for installing Massif (https://github.com/viatra/massif/wiki/DevelopersGuide), we are getting a bit lost on how we should proceed in order to fix it.

In case you really used the Oomph setup for Massif to create a development environment with Massif source code imported, you just have to make sure you have the latest changes fetched from the repository and have an up-to-date Target Platform so you don't have any compile errors. You can re-run the Oomph setup tasks through Help -> Perform Setup Tasks if you haven't done that for a long time.

**Comment by GaraziJuez** [comment] 2017-08-09 11:18
Thank you for your response! 
We are trying to check what you have just explained us right now. I will give you feedback as soon as we have tried it.
Just a brief question: does it work with Eclipse Neon as well? In other words, is Massif dependent on Eclipse version?
Thanks!
Garazi

**Comment by abelhegedus** [comment] 2017-08-09 11:20
> does it work with Eclipse Neon as well? In other words, is Massif dependent on Eclipse version?

It should work with any Eclipse from Mars and beyond (Neon, Oxygen), probably even earlier but I'm not sure.

**Comment by GaraziJuez** [comment] 2017-08-09 11:50
Thank you and sorry for disturbing you once again, however, we would like to be sure we are following the good procedure. 
First of all, and just for clarification, we are interested on cloning the Master version of Massif and not on Oomph. We have decided to go through Massif 0.6.0 since "Exporting to Simulink" issue is already fixed.

In summary, we would like to understand if the following steps are right:

1) Install Eclipse Neon.
2) Clone the Massif "Master" branch from https://github.com/viatra/massif (Massif 0.6.0).
3)  Install VIATRA Query and Transformation SDK 1.2.0  from http://download.eclipse.org/viatra/updates/release/    (Does it work for newer versions of Viatra as well?)

Thanks.
Garazi

**Comment by imbur** [comment] 2017-08-09 12:03
The high-level steps described below seem complete to me, however, I would recommend using VIATRA 1.2 for now. Let us know if you encounter any issues.
FYI: There is an ongoing work on the [`matlab-engine`](https://github.com/viatra/massif/tree/matlab-engine) branch. After it is merged, the newest version of VIATRA will be supported as well.

**Comment by GaraziJuez** [comment] 2017-08-09 12:23
Thanks for the help and the information.
We get this issue when installing VIATRA 1.2:
![viatraissue](https://user-images.githubusercontent.com/20126983/29120892-9c429910-7d0c-11e7-810b-a368fad74187.png) 
![viatraissue2](https://user-images.githubusercontent.com/20126983/29121068-4dda9538-7d0d-11e7-94c6-11062d206e71.png)

Therefore, we have tried to fix that issue by installing Viatra 1.6. After doing so, the installation process is completed. However, we obtain different errors related to many plugins.

**Comment by abelhegedus** [comment] 2017-08-09 12:44
Please try with VIATRA 1.5.x or 1.2.1 (there was a specific problem in EMF 2.12 that may cause problems with VIATRA 1.2.0 and we added an upper version constraint, which was later removed after working around the issue).

**Comment by GaraziJuez** [comment] 2017-08-10 11:12
Dear Abel,

thank you for your inputs. Finally, we got it working by using VIATRA 1.5.0 (with 1.2.1 was not working because of Xtend version incompatibilities in Neon).
We have tried importing and exporting and "more or less" works fine. However, we are still facing some issues with exporting functionality:

1) Seemengly there is some issue when the design holds subsystems (Subsystem exporting): 
 "Subsystem block parameter 'ActiveVariant' is read-only ". 
We have already double-checked that the corresponding block is not read-only.
2) If the design contains a "Scope" block, after importing and exporting it again, this block is transformed into "floating scope" type.

Thank you!
Garazi

**Comment by abelhegedus** [comment] 2017-08-10 11:24
> Seemengly there is some issue when the design holds subsystems (Subsystem exporting):
"Subsystem block parameter 'ActiveVariant' is read-only ".
We have already double-checked that the corresponding block is not read-only.

Maybe ActiveVariant is a parameter that can be read, but cannot be written since it is a sort of "derived" parameter. Are you using [Variant Subsystems](https://www.mathworks.com/help/simulink/examples/variant-subsystems.html)?

> If the design contains a "Scope" block, after importing and exporting it again, this block is transformed into "floating scope" type.

Massif import/export is almost completely generic. It will read all parameters provided by Matlab during import and set all parameters during Export. We have an [issue](https://github.com/viatra/massif/issues/30) related to default property values, maybe Matlab somehow considers the properties set by the exporter to be different from what is the default value. E.g. maybe the floating property of the Scope is not a real parameter and the default setting is that it floats, but the library has a non-floating block that you can add to your model...

**Comment by GaraziJuez** [comment] 2017-08-10 12:02
Thanks :-)
1) No, we are not using Variant Subsystems.
2) Thanks for clarifying this issue. Does this mean we would need to develop our own custom solution here? Or what would be your suggestion? Our main issue here is that when this happens no connections between blocks appear at all.

**Comment by imbur** [comment] 2017-08-10 12:31
Could you open an issue and provide a minimal example to reproduce the
scope-related problem? I'll try to look into it soon. Thank you!

**Comment by GaraziJuez** [comment] 2017-08-11 09:36
Dear Burton,

sure, I will do that. Thank you!

Garazi

**Closed** 2018-07-10 13:39 UTC
